# Generated by Django 2.1.2 on 2018-11-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cashentry',
            fields=[
                ('entryid', models.AutoField(db_column='EntryID', primary_key=True, serialize=False)),
                ('onec', models.IntegerField()),
                ('fivec', models.IntegerField()),
                ('tenc', models.IntegerField()),
                ('twfvc', models.IntegerField()),
                ('oned', models.IntegerField()),
                ('twod', models.IntegerField()),
                ('fived', models.IntegerField()),
                ('tend', models.IntegerField()),
                ('twntd', models.IntegerField()),
                ('staffid', models.IntegerField(db_column='StaffID')),
                ('locid', models.IntegerField(db_column='LocID')),
                ('shifttime', models.CharField(db_column='ShiftTime', max_length=40)),
                ('entrydate', models.DateField(db_column='EntryDate')),
                ('totalcash', models.FloatField()),
                ('recount', models.CharField(db_column='Recount', max_length=40)),
            ],
            options={
                'db_table': 'cashentry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('staffid', models.AutoField(db_column='StaffID', primary_key=True, serialize=False)),
                ('staffname', models.CharField(db_column='StaffName', max_length=255)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('locid', models.AutoField(db_column='LocID', primary_key=True, serialize=False)),
                ('locname', models.CharField(db_column='LocName', max_length=255)),
            ],
            options={
                'db_table': 'locations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patientpay',
            fields=[
                ('datepay', models.DateField()),
                ('ptnamepay', models.CharField(blank=True, max_length=40, null=True)),
                ('ptidpay', models.CharField(blank=True, max_length=20, null=True)),
                ('otherpay', models.CharField(blank=True, max_length=40, null=True)),
                ('amountpay', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('staffid', models.IntegerField(blank=True, db_column='StaffID', null=True)),
                ('locid', models.IntegerField(db_column='LocID')),
                ('entryidp', models.AutoField(db_column='EntryIDp', primary_key=True, serialize=False)),
                ('payitem', models.CharField(blank=True, max_length=40, null=True)),
                ('paytype', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'patientpay',
                'managed': False,
            },
        ),
    ]
