# Generated by Django 2.1.2 on 2019-03-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainforms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('entryid', models.AutoField(primary_key=True, serialize=False)),
                ('deletedentry', models.CharField(max_length=200)),
            ],
        ),
    ]
