# Generated by Django 2.1.2 on 2019-04-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainforms', '0003_auto_20190321_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audit',
            old_name='deletedentry',
            new_name='modifiedentry',
        ),
        migrations.RenameField(
            model_name='audit',
            old_name='deletedentryid',
            new_name='modifiedentryid',
        ),
        migrations.AlterField(
            model_name='audit',
            name='deletedate',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
